version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-volume:/docker-entrypoint-initdb.d
      - mongodb-persistence:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

networks:
  mongodb:
    driver: bridge
volumes:
  mongodb-volume:
  mongodb-persistence: