const productsTagsEs = [
    'Comida',
    'Pan',
    'Embutidos',
    'Lacteos',
    'Ceriales',
    'Semillas',
    'Orgánico',
    'Sin gluten',
    'Vegano',
    'Vegetariano',
    'Sin lactosa',
    'Sin azúcar añadida',
    'Bajo en grasas',
    'Bajo en calorías',
    'Alto en fibra',
    'Sin conservantes',
    'Producto local',
    'Bebida',
    'Cafetería y té',
    'Refrescos y jugos',
    'Vinos y licores',
    'Ingredientes básicos',
    'Frutas y Verduras',
    'Botana y Antojos',
    'Alcohol',
    'Medicina',
    'Eco-Friendly',
    'Exclusivo',
    'Electrónica',
    'Ropa',
    'Calzado',
    'juegos y Jugetes',
    'Salud',
    'Productos para el cuerpo',
    'fragancias y esencias',
    'Herramientas',
    'Limpieza',
    'Hogar',
    'Jardineria',
    'Reposteria',
    'Otros'
];
const productsTagsEn = [
    'Food',
    'Bread',
    'Cold Cuts',
    'Dairy',
    'Cereals',
    'Seeds',
    'Organic',
    'Gluten-Free',
    'Vegan',
    'Vegetarian',
    'Lactose-Free',
    'No Added Sugar',
    'Low in Fat',
    'Low in Calories',
    'High in Fiber',
    'Preservative-Free',
    'Local Product',
    'Beverage',
    'Coffee and Tea',
    'Soda and Juices',
    'Wines and liquors',
    'Basic Ingredients',
    'Fruits and Vegetables',
    'Snacks',
    'Alcohol',
    'Medicine',
    'Eco-Friendly',
    'Exclusive',
    'Electronics',
    'Clothing',
    'Footwear',
    'Games and Toys',
    'Health',
    'Body Products',
    'Fragrances and Essences',
    'Tools',
    'Cleaning',
    'Home',
    'Gardening',
    'Bakery',
    'Others'
];

export {
    productsTagsEs ,
    productsTagsEn
};